Bank account category
darrynten/sage-one-php pull request #111
Opened 2017-08-03 13:31 UTC by igorsergiichuk

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

## The problem

Bank account category Model Test was missing

## How I resolved it

Added Bank account category Model Test + mocks

## How to verify it

Test it!

Notify the following people: @darrynten

2017-08-04 07:50 UTC, darrynten reviewed
Not sure what's going on here, which one is correct?

2017-08-04 07:50 UTC, darrynten commented on tests/mocks/BankAccountCategory/POST_BankAccountCategory_Save_RESP.json
> +}
Which is correct? The red or the green?

2017-08-04 08:06 UTC, igorsergiichuk commented on tests/mocks/BankAccountCategory/POST_BankAccountCategory_Save_RESP.json
> +}
green is correct. SAGE docs give us a blank response. @fergusdixon contacted them. They wrote a letter which indicates that RESP is the same as REQ.

2017-08-04 09:39 UTC, darrynten submitted a review, later dismissed

2017-08-04 16:39 UTC, darrynten commented
These seem to be failing on Travis due to missing mocks

<img width="863" alt="screen shot 2017-08-04 at 6 37 34 pm" src="https://user-images.githubusercontent.com/3657251/28977885-22afadf2-7944-11e7-9eb7-e9035d16b6ce.png">

2017-08-06 21:14 UTC, darrynten requested changes
A double quote that should be single

2017-08-06 21:14 UTC, darrynten commented on tests/SageOne/Models/BankAccountCategoryModelTest.php
> +            $model->description = "sample string 1";
This should be single quotes :) Same in the next method

2017-08-11 15:36 UTC, darrynten approved these changes
Nice!

2017-08-11 16:14 UTC, merged