Suggestion: do not describe all properties twice
darrynten/sage-one-php pull request #17
Opened 2017-07-08 17:18 UTC by make-it-git

May be it is enough to describe them only in $fields. $fields are self explanatory

2017-07-08 17:38 UTC, darrynten requested changes
Reducing complexity in __get() suggestion

2017-07-08 17:38 UTC, darrynten commented on src/BaseModel.php
> +            return $this->fieldsData[$key];
We can simplify, and flatten this a bit and reduce complexity

```php
public function __get($key)
{
    if (array_key_exists($key, $this->fields)) {
        if (array_key_exists('default', $this->fields[$key])) {
            // we can leave early
            return $this->fields[$key]['default'];
        }

        if (array_key_exists($key, $this->fieldsData)) {
            return $this->fieldsData[$key];
        }

        return null;
    }

    // normal exception handler
```

I have not tested but it should work

2017-07-08 17:42 UTC, darrynten commented on src/BaseModel.php
> +        $value = $this->__get($key);
Good call this 🍺

2017-07-08 17:42 UTC, darrynten commented on tests/SageOne/Models/AccountModelTest.php
>          // (var_dump($accountModel->toJson()));
We can't have commented out code getting committed ;)

2017-07-08 17:43 UTC, darrynten commented on tests/SageOne/Models/ExampleModelTest.php
> -
Any particular reason for these assertions to not be there?

2017-07-08 17:46 UTC, darrynten commented on src/BaseModel.php
> +            if (array_key_exists('default', $this->fields[$key])) {
Where does the `default` key come from?

2017-07-08 17:49 UTC, make-it-git commented on tests/SageOne/Models/ExampleModelTest.php
> -
This test will be rewritten with new methods, there is already this check.
This one checks not only fields, but also other properties

2017-07-08 17:50 UTC, make-it-git commented on src/BaseModel.php
> +            if (array_key_exists('default', $this->fields[$key])) {
I guess from there docs.
If key is nullable, we are allowed not to specify it because it is null by default

2017-07-08 17:51 UTC, make-it-git commented on src/BaseModel.php
> +            if (array_key_exists('default', $this->fields[$key])) {
May be this is not required.
May be throw exception in __get if data is not loaded?

2017-07-08 17:51 UTC, make-it-git commented on src/BaseModel.php
> +        $value = $this->__get($key);
Is there better way?

2017-07-08 19:03 UTC, darrynten commented on src/BaseModel.php
> +            if (array_key_exists('default', $this->fields[$key])) {
So it's maybe that we have potential `default` and `required` properties to add to the fields map?

2017-07-08 19:05 UTC, darrynten commented on src/BaseModel.php
> +        $value = $this->__get($key);
I think that's the right way

2017-07-10 10:42 UTC, darrynten requested changes
So far so good, very minor requests

2017-07-10 10:42 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +
I think we add additional checks on min/max/regex etc here

2017-07-10 10:42 UTC, darrynten commented on src/Models/AccountCategory.php
> +            'readonly' => false,
This now has a `required` on it if we look at the docs and our new rules

https://accounting.sageone.co.za/api/1.1.2/Help/ResourceModel?modelName=AccountCategory

2017-07-10 11:46 UTC, darrynten approved these changes

2017-07-10 11:48 UTC, merged