Account model custom methods
darrynten/sage-one-php pull request #21
Opened 2017-07-10 11:04 UTC by make-it-git

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

## The problem

Add custom methods to Account. It includes GetAccountsByCategoryId/{id}, GetWithSystemAccounts, GetChartofAccounts

## How I resolved it

Similar to all() and get() methods.

Notify the following people: @darrynten

2017-07-10 12:26 UTC, darrynten requested changes
Looking good, some change requests included

2017-07-10 12:26 UTC, darrynten commented on src/BaseModel.php
> +
Too many newlines here

2017-07-10 12:26 UTC, darrynten commented on src/Exception/ExceptionMessages.php
> +        10123 => 'Validation type is invalid',
This was moved into the array below, perhaps the merge didn't go so smoothly 🙃

2017-07-10 12:26 UTC, darrynten commented on src/Models/Account.php
> +        return json_encode($results, JSON_PRESERVE_ZERO_FRACTION);
We can't return JSON here, we need to fill and return Objects like we do in `all` and `get` calls in the base class

2017-07-10 12:26 UTC, darrynten commented on src/Models/Account.php
> +        return json_encode($results, JSON_PRESERVE_ZERO_FRACTION);
As per above

2017-07-10 12:26 UTC, darrynten commented on src/Models/Account.php
> +        return json_encode($results, JSON_PRESERVE_ZERO_FRACTION);
And once more

2017-07-10 12:37 UTC, make-it-git commented on src/Models/Account.php
> +        return json_encode($results, JSON_PRESERVE_ZERO_FRACTION);
But all() in base class does json_encode (I've added JSON_PRESERVE_ZERO_FRACTION to eliminate some errors when double without fraction is converted into integer)

2017-07-10 12:40 UTC, darrynten commented on src/Models/Account.php
> +        return json_encode($results, JSON_PRESERVE_ZERO_FRACTION);
hmm, all() is supposed to return an object representation of the collection, perhaps that code was not written correctly

2017-07-10 14:31 UTC, darrynten requested changes
I'm really liking where this is going

2017-07-10 14:31 UTC, darrynten commented on tests/mocks/Example/GET_Example_Get.json
> +        "SomeBoolean": true
I think it would be more functional to have completely different example data in the second result

2017-07-10 14:45 UTC, make-it-git commented
Should we ignore codeclimate warning in this case?

2017-07-10 17:56 UTC, make-it-git commented on tests/mocks/Example/GET_Example_Get.json
> +        "SomeBoolean": true
@darrynten Done

2017-07-10 18:32 UTC, darrynten commented on src/Exception/ExceptionMessages.php
> +    public static $modelCollectionErrorMessages = [
I have marked this as acceptable on codacy

2017-07-10 19:54 UTC, darrynten requested changes
I really like the way this is getting refactored, some small formatting requests

2017-07-10 19:54 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +            'http://localhost:8082' . $url,
We should drop the `http:` protocol part here and also use `sprintf`

2017-07-10 19:54 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +            sprintf('%s/GET_%s_Get.json', $className, $className));
I think this should be reformatted for readability:

```php
$model = $this->setUpRequestMock(
    $class,
    $path,
    'GET',
    sprintf(
        '%s/GET_%s_Get.json',
        $className,
        $className
    )
);
```

and I think the `GET` should be the first parameter as it is more consistent with how you ask or the request (get class at path)

2017-07-10 19:54 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +        $model = $this->setUpRequestMock($class, $path, 'GET',
This formatting should be expanded too

2017-07-10 19:54 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +            sprintf('%s/POST_%s_Save_RESP.json', $className, $className),
And again here :)

2017-07-11 07:28 UTC, darrynten requested changes
Some incorrect constants and a question

2017-07-11 07:28 UTC, darrynten commented on src/Exception/ModelException.php
> +    const VALIDATION_TYPE_ERROR = 10123;
These aren't the correct numbers, these are not supposed to be in here as they're in the ValidationException class

2017-07-11 07:28 UTC, darrynten commented on src/Models/ModelCollection.php
> +        if (array_search($key, $this->keys) !== false) {
Shouldn't this be `array_key_exists`?

2017-07-11 07:33 UTC, make-it-git commented on src/Models/ModelCollection.php
> +        if (array_search($key, $this->keys) !== false) {
No, because keys here are 0,1,2

2017-07-11 07:59 UTC, darrynten commented on src/Models/ModelCollection.php
> +        if (array_search($key, $this->keys) !== false) {
I'm confused, is the key that's getting passed in 0,1,2 etc, or are the keys themselves 0,1,2?

It looks like the keys are `['totalResults', 'returnedResults', 'results']` so are we not passing that value into the __get?

2017-07-11 08:17 UTC, make-it-git commented on src/Models/ModelCollection.php
> +        if (array_search($key, $this->keys) !== false) {
['key1', 'key2'] is the same as [0 => 'key1', 1 => 'key2']

2017-07-11 08:25 UTC, darrynten commented on src/Models/ModelCollection.php
> +        if (array_search($key, $this->keys) !== false) {
Is this doing `__get('totalResults') { if (array_search('totalResults', ['totalResults', 'results'] !== false) {`?

2017-07-11 08:32 UTC, darrynten commented on src/Exception/ValidationException.php
>       * @var integer $code The error code (as per above) [10200 is Generic code]
The comment default doesn't match the default in the method

2017-07-11 09:17 UTC, make-it-git commented on src/Models/ModelCollection.php
> +        if (array_search($key, $this->keys) !== false) {
Yes

2017-07-11 12:16 UTC, mxnr commented on src/BaseModel.php
> +        return new ModelCollection(get_class($this), $this->config, $results);
It's better to use `ClassName::class` here

2017-07-11 12:17 UTC, mxnr commented on src/Exception/ExceptionMessages.php
> +    public static $validationMessages = [
Please add a phpdoc with var type

2017-07-11 12:18 UTC, mxnr commented on src/Exception/ModelCollectionException.php
> + * @package SageOne
Are you sure that we use packages?

2017-07-11 12:18 UTC, mxnr commented on src/Models/Account.php
> +    public function getAccountsByCategoryId(string $id)
$id param missed in phpdoc

2017-07-11 12:19 UTC, mxnr commented on src/Models/ModelCollection.php
> +            throw new ModelCollectionException(ModelCollectionException::MISSING_REQUIRED_PROPERTY, 'ReturnedResults');
Line is more than 120 symbols here

2017-07-11 12:19 UTC, mxnr commented on src/Models/ModelCollection.php
> +    public function __construct($class, $config, \stdClass $results)
Phpdoc missed

2017-07-11 12:21 UTC, mxnr commented on tests/SageOne/Models/BaseModelTest.php
> +    protected function setUpRequestMock(string $method, string $class, string $path, string $mockFileResponse = null, string $mockFileRequest = null)
Phpdoc missed

2017-07-11 22:32 UTC, darrynten commented on src/Models/ModelCollection.php
> +        if (array_search($key, $this->keys) !== false) {
But isn't that the same as `array_key_exists`?

Excuse me if I'm being silly 😸

2017-07-11 23:04 UTC, darrynten commented on src/Models/ModelCollection.php
> +        if (array_search($key, $this->keys) !== false) {
It makes sense to me now!

2017-07-12 06:30 UTC, darrynten approved these changes

2017-07-12 06:31 UTC, merged