Base model test extend
darrynten/sage-one-php pull request #26
Opened 2017-07-10 18:32 UTC by make-it-git

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #23 

## The problem

We need to do strict checking on described fields

## Questions

Should we validate regex equality (duplicate regexp)?

Notify the following people: @darrynten

2017-07-10 20:03 UTC, darrynten requested changes

2017-07-10 20:03 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +                switch($options['type']) {
A switch with less than three branches is inefficient, we should use an if statement instead.

2017-07-11 07:38 UTC, darrynten requested changes
Some notes

2017-07-11 07:38 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +                if (array_search($option, ['type', 'nullable', 'readonly', 'default', 'required', 'min', 'max', 'regex']) === false) {
I think this should be `array_key_exists`?

2017-07-11 07:38 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +            foreach ($options as $option => $_) {
Would `array_keys` not be better here to avoid an unused assignment to `$_`?

2017-07-11 07:38 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +                $this->assertTrue(isset($value[$name]['default']), sprintf('"default" for %s is not present', $name));
If I remember correctly `isset` returns false for `null` and `array_key_exists` returns true for `null`, so if there is a case where the default can be null then this will fail

2017-07-11 07:38 UTC, darrynten commented on tests/SageOne/Models/ExampleModelFieldsTest.php
> +                'default' => 'some default value',
I think we need to add another test, for `stringWithNullDefault` here

2017-07-11 13:36 UTC, mxnr commented on tests/SageOne/Models/BaseModelTest.php
> +            foreach (array_keys($options) as $option) {
It's better to use PHPUNit data providers in such cases

2017-07-11 13:38 UTC, mxnr commented on tests/SageOne/Models/BaseModelTest.php
> +
IMO this test is very huge. Consuming to split it into smaller parts. You can use PHPUnit chaining system for that.

2017-07-11 23:15 UTC, darrynten requested changes

2017-07-11 23:15 UTC, darrynten commented on tests/mocks/Example/GET_Example_Get_xx.json
> +  "StringWithNullDefault": "another string",
Shouldn't this be `null`?

2017-07-12 10:56 UTC, darrynten approved these changes

2017-07-12 10:56 UTC, merged