Accountopeningbalance model
darrynten/sage-one-php pull request #27
Opened 2017-07-10 19:03 UTC by make-it-git

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #24 

## Notes

Upon successfull saving we load data back into model from response

...

Notify the following people: @darrynten

2017-07-11 07:44 UTC, darrynten requested changes
Change requests

2017-07-11 07:44 UTC, darrynten commented on src/BaseModel.php
> +        $this->loadResult($data);
I think we perhaps need to add a test for if bad data comes back from the API for this?

2017-07-11 07:44 UTC, darrynten commented on src/Exception/ModelException.php
> +    const VALIDATION_TYPE_ERROR = 10123;
This is moved to the ValidationException

2017-07-11 07:44 UTC, darrynten commented on src/Models/ModelCollection.php
> +        if (array_search($key, $this->keys) !== false) {
See comments on previous PR

2017-07-11 08:23 UTC, darrynten requested changes

2017-07-11 08:23 UTC, darrynten commented on src/Exception/ValidationException.php
>       * @var integer $code The error code (as per above) [10200 is Generic code]
This comment default was not updated

2017-07-11 08:23 UTC, darrynten commented on tests/SageOne/Models/AccountModelTest.php
> +        $this->assertInstanceOf(AccountCategory::class, $account->category);
These tests should be more extensive.

We're only checking inside 1 account results, and we're not checking the rest of the keys in the account result, nor the keys in the $allAccounts itself.

Our unit tests need to be very extensive and check all possible angles on a result - for example, this should be checking `$allAccounts` on `totalResults` etc too.

This applies to all our testing, we must use very defensive unit tests to save us time in the future.

2017-07-11 08:23 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +        $this->assertInstanceOf($class, $response);
This is just inserting the request and is not checking the response as far as I can tell?

This test should create an instance, load data, check it, then change the actual data, save() it, and check that result is as expected.

 I could be completely missing something though 😺

2017-07-11 08:23 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +            'http://localhost:8082' . $url,
Drop the protocol `http:` part here

2017-07-11 08:23 UTC, darrynten commented on tests/SageOne/Models/ModelCollectionTest.php
> +        $results->TotalResults = 0;
Why are these ProperCase and not camelCase?

2017-07-11 08:35 UTC, make-it-git commented on tests/SageOne/Models/ModelCollectionTest.php
> +        $results->TotalResults = 0;
Because it is returned in this way from API so to simplify processing we do not make modification on returned results (we can pass result from API into ModelCollection constructor)

2017-07-11 08:36 UTC, make-it-git commented on tests/SageOne/Models/BaseModelTest.php
> +        $this->assertInstanceOf($class, $response);
There is callback to check actual response

2017-07-11 08:47 UTC, darrynten commented on tests/SageOne/Models/ModelCollectionTest.php
> +        $results->TotalResults = 0;
When we pass it results are we not passing in processed results?

We shouldn't put unprocessed results into a collection, should we?

If we were matching the API would we not pass in JSON instead of an object?

2017-07-11 08:51 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +        $this->assertInstanceOf($class, $response);
Sure, however we need to do PRs in order of opening, and these branches keep getting merged into each other, which can be confusing and introduce bad merge bugs, like what happened with the validation.

If we branch off a branch that PR must be into the branch it came from, not dev (like I opened mine into yours) and if we do that it must be marked.

We must not branch off a PR and then open another PR into dev.

Because this happened we have to be very careful.

In the future when we do 1 PR = 1 Feature this will be easier.

I understand it's the beginning so it's OK at this moment, but after these are in we need to stick to that rule.

2017-07-11 13:32 UTC, mxnr commented on src/Models/Account.php
> +    public function getAccountsByCategoryId(string $id)
Missed $id value phpdoc comment

2017-07-11 13:33 UTC, mxnr commented on src/Exception/ExceptionMessages.php
> +    public static $modelCollectionErrorMessages = [
Phpdoc should be added here

2017-07-11 13:33 UTC, mxnr commented on src/Exception/ExceptionMessages.php
> +    public static $validationMessages = [
Phpdoc should be added here

2017-07-11 13:35 UTC, mxnr commented on src/Models/ModelCollection.php
> +        if (array_search($key, $this->keys) !== false) {
Could it be replaced with `isset($this->keys[$key])`? This is significantly faster.

2017-07-11 13:59 UTC, make-it-git commented on src/Models/Account.php
> +    public function getAccountsByCategoryId(string $id)
Added in  PR #21

2017-07-11 13:59 UTC, make-it-git commented on src/Exception/ExceptionMessages.php
> +    public static $modelCollectionErrorMessages = [
Added in  PR #21

2017-07-11 13:59 UTC, make-it-git commented on src/Exception/ExceptionMessages.php
> +    public static $validationMessages = [
Added in  PR #21

2017-07-11 14:20 UTC, make-it-git commented on tests/SageOne/Models/ModelCollectionTest.php
> +        $results->TotalResults = 0;
handleRequest inside RequestHandler returns stdClass (missing second argument in json_decode)

2017-07-11 22:58 UTC, darrynten commented on tests/SageOne/Models/ModelCollectionTest.php
> +        $results->TotalResults = 0;
I see so that means this state is the same as the state after we json_decode a response?

2017-07-12 08:25 UTC, darrynten commented
There are some small conflicts here :)

2017-07-12 13:23 UTC, darrynten commented on tests/SageOne/Models/AccountOpeningBalanceModelTest.php
> +        $this->expectExceptionMessage('Model "AccountOpeningBalance" Received namespaced class "DarrynTen\SageOne\Models\double" when defined type is "boolean" Property is referencing an undefined, n
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Line exceeds 120 characters; contains 220 characters](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=767606)

2017-07-12 13:23 UTC, darrynten commented on tests/SageOne/Models/AccountOpeningBalanceModelTest.php
> +        $this->expectExceptionMessage('Model "AccountOpeningBalance" Defined key "reason" not present in payload A property is missing in the loadResult payload');
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Line exceeds 120 characters; contains 163 characters](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=767606)

2017-07-12 13:23 UTC, darrynten commented on tests/SageOne/Models/AccountOpeningBalanceModelTest.php
> +        $this->verifyGetId(AccountOpeningBalance::class, 2, function ($model) {
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused local variables such as '$model'.](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=767606)

2017-07-12 13:23 UTC, darrynten commented on tests/SageOne/Models/AccountOpeningBalanceModelTest.php
> +class AccountOpeningBalanceModelTest extends BaseModelTest
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [The class AccountOpeningBalanceModelTest has 11 public methods. Consider refactoring AccountOpeningBalanceModelTest to keep number of public methods under 10.](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=767606)

2017-07-12 13:23 UTC, darrynten commented on tests/SageOne/Models/AccountOpeningBalanceModelTest.php
> +        $this->verifyInject(AccountOpeningBalance::class, function ($model, $data) {
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused local variables such as '$data'.](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=767606)

2017-07-12 13:23 UTC, darrynten commented on tests/SageOne/Models/AccountOpeningBalanceModelTest.php
> +class AccountOpeningBalanceModelTest extends BaseModelTest
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [The class AccountOpeningBalanceModelTest has 11 non-getter- and setter-methods. Consider refactoring AccountOpeningBalanceModelTest to keep number of methods under 10.](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=767606)

2017-07-12 13:23 UTC, darrynten commented
![Codacy](https://www.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           
```


See the complete overview on [Codacy](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=767606&bid=4900344)

2017-07-12 20:09 UTC, darrynten commented on tests/SageOne/Models/AccountOpeningBalanceModelTest.php
> +class AccountOpeningBalanceModelTest extends BaseModelTest
This is OK

2017-07-12 20:09 UTC, darrynten commented on tests/SageOne/Models/AccountOpeningBalanceModelTest.php
> +        $this->verifyGetId(AccountOpeningBalance::class, 2, function ($model) {
This should get fixed

2017-07-12 20:09 UTC, darrynten commented on tests/SageOne/Models/AccountOpeningBalanceModelTest.php
> +        $this->expectExceptionMessage('Model "AccountOpeningBalance" Defined key "reason" not present in payload A property is missing in the loadResult payload');
This is OK

2017-07-12 20:09 UTC, darrynten commented on tests/SageOne/Models/AccountOpeningBalanceModelTest.php
> +        $this->expectExceptionMessage('Model "AccountOpeningBalance" Received namespaced class "DarrynTen\SageOne\Models\double" when defined type is "boolean" Property is referencing an undefined, n
This is OK

2017-07-12 20:10 UTC, darrynten commented on tests/SageOne/Models/AccountOpeningBalanceModelTest.php
> +class AccountOpeningBalanceModelTest extends BaseModelTest
This is OK

2017-07-12 20:10 UTC, darrynten commented on tests/SageOne/Models/AccountOpeningBalanceModelTest.php
> +        $this->verifyInject(AccountOpeningBalance::class, function ($model, $data) {
This should get fixed

2017-07-12 20:11 UTC, darrynten commented on src/BaseModel.php
> +        // otherwise ApiException was thrown and this line can not be reached
This makes sense, but can you wrap the multi-line like this style:

```
/**
 * This style
 */
```

instead of `//` style?

2017-07-12 20:13 UTC, darrynten requested changes
2 small change requests :)

2017-07-12 20:13 UTC, darrynten commented on src/Exception/ValidationException.php
> +    public function __construct($code, $extra = '')
This should pass in the default

2017-07-12 20:13 UTC, darrynten commented on tests/mocks/AccountOpeningBalance/POST_AccountOpeningBalance_Save_InvalidResponse2.json
> +
There shouldn't be a newline at the top of the file

2017-07-12 20:27 UTC, darrynten approved these changes

2017-07-12 20:28 UTC, merged