Supplier model
darrynten/sage-one-php pull request #28
Opened 2017-07-12 14:12 UTC by igorsergiichuk

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

## The problem

...

## How I resolved it

...

## How to verify it

...

## Questions

...

## Notes

...

Notify the following people: @darrynten

2017-07-12 14:17 UTC, darrynten commented on src/Models/Supplier.php
> +
This is where StyleCI is failing :)

2017-07-12 14:31 UTC, darrynten requested changes

2017-07-12 14:31 UTC, darrynten commented on src/Models/Supplier.php
> + *
You need to add some information here, and also leave a link to the documentation for this model

2017-07-12 14:58 UTC, igorsergiichuk reviewed
Added a link to Supplier parameters:
https://accounting.sageone.co.za/api/1.1.2/Help/Api/POST-Supplier-Save

2017-07-12 14:58 UTC, igorsergiichuk commented on src/Models/Supplier.php
> +
I've already fixed that.) Thanks. The only thing I need to pull is review.

2017-07-12 15:32 UTC, darrynten requested changes

2017-07-12 15:32 UTC, darrynten commented on src/Models/Supplier.php
> + * https://accounting.sageone.co.za/api/1.1.2/Help/Api/POST-Supplier-Save
This link should be https://accounting.sageone.co.za/api/1.1.2/#bookmark_Supplier

The link you attached for is specific to the save method

2017-07-12 16:11 UTC, mxnr submitted a review, later dismissed
Looks good for me👍

2017-07-12 16:13 UTC, darrynten commented
@mxnr it's looking good, we're just waiting on the tests and mocks now :) But I agree, @igorsergiichuk is doing a great job here

2017-07-12 17:55 UTC, darrynten commented on tests/SageOne/Models/AccountModelTest.php
> +            $this->assertCount(2, $results);
Thanks for changing this

2017-07-12 18:06 UTC, darrynten requested changes

2017-07-12 18:06 UTC, darrynten commented on src/Models/Supplier.php
> +            'type' => 'SupplierCategory',
Does this model exist yet? If it doesn't then we will need to add it as part of this PR

2017-07-13 12:45 UTC, darrynten commented
Superseded by #30

2017-07-13 12:45 UTC, closed without merging