Tax invoice tests
darrynten/sage-one-php pull request #48
Opened 2017-07-17 18:57 UTC by make-it-git

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

## The problem

How to validate all passed parameters in setUpRequestMock of BaseModelTest?
Example:

$model = new TaxInvoice($this->config);
$parameters = ['key' => 'value']; // https://accounting.sageone.co.za/api/1.1.2/Help/Api/POST-TaxInvoice-Email
$model->email($parameters);

I guess we need to check in tests that what is passed as third argument ($options) in request() is exactly the same.

Currently it checks 'headers' array in query, and apikey.

Notify the following people: @darrynten

2017-07-17 21:12 UTC, darrynten requested changes
It's looking good, I'm just wanting some documentation for the emailing, and the new parameters around that.

Thanks!

2017-07-17 21:12 UTC, darrynten commented on tests/SageOne/Models/TaxInvoiceModelTest.php
> +            $trackingCode = '$trackingCode'; // TODO is there a better way?
That's odd?

2017-07-17 21:12 UTC, darrynten commented on tests/SageOne/Models/TaxInvoiceModelTest.php
> +            $this->assertEquals("sample string 2", $model2->customer->defaultPriceListName);
This should be single quotes instead of double

2017-07-17 21:12 UTC, darrynten commented on src/Models/TaxInvoice.php
> +    public function email(array $parameters)
Can you please document what these parameters are?

2017-07-17 21:12 UTC, darrynten commented on tests/SageOne/Models/TaxInvoiceModelTest.php
> +            'customer_CurrencyId' => [
They have some strange conventions hey 🙃

2017-07-18 07:25 UTC, darrynten requested changes

2017-07-18 07:25 UTC, darrynten commented on src/Models/TaxInvoice.php
> +        return $this->request->request('POST', $this->endpoint, 'Calculate');
Can you please explain how it know what to calculate here?

2017-07-18 10:47 UTC, make-it-git commented on src/Models/TaxInvoice.php
> +        return $this->request->request('POST', $this->endpoint, 'Calculate');
https://accounting.sageone.co.za/api/1.1.2/Help/Api/POST-TaxInvoice-Calculate

It just says that it calculates result

2017-07-18 13:59 UTC, darrynten commented on src/Models/TaxInvoice.php
> +        return $this->request->request('POST', $this->endpoint, 'Calculate');
That's fine, but how does it know which payload to send through?

The req/resp for them is quite large, and the other post methods send through a payload as defined in their model with the `save()` method - this isn't using a 4th param for the params.

2017-07-18 22:14 UTC, darrynten commented on src/Models/TaxInvoice.php
> +        return $this->request->request('POST', $this->endpoint, 'Calculate');
@make-it-git this might be similar to the calculate call in #56 - if you need any help here please give me or @fergusdixon a shout

2017-07-19 11:03 UTC, make-it-git commented on tests/SageOne/Models/TaxInvoiceModelTest.php
> +            $trackingCode = '$trackingCode'; // TODO is there a better way?
Is there better way to access property with name which starts with $?

2017-07-19 11:03 UTC, make-it-git commented on tests/SageOne/Models/TaxInvoiceModelTest.php
> +            'customer_CurrencyId' => [
There are may inconsistencies in api

2017-07-19 16:06 UTC, darrynten approved these changes
Really nice solution to the Calculate

@igorsergiichuk @fergusdixon @kiproping check this solution, really clever and uses a new toArray() method - you'll have this available to you after you pull latest dev into your active branches.

2017-07-19 16:06 UTC, darrynten commented on src/Models/TaxInvoice.php
> +     *   }
I like the way you documented this :)

2017-07-19 16:06 UTC, darrynten commented on tests/SageOne/Models/TaxInvoiceModelTest.php
> +            $trackingCode = '$trackingCode'; // TODO is there a better way?
I'm honestly not sure, I think we need to see what happens

2017-07-19 17:28 UTC, merged