Supplier adjustment model
darrynten/sage-one-php pull request #56
Opened 2017-07-18 21:01 UTC by igorsergiichuk

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

## The problem

SupplierAdjustment model was missing

## How I resolved it

Added SupplierAdjustment model + tests

## How to verify it

Test it!

Notify the following people: @darrynten

2017-07-18 22:08 UTC, darrynten requested changes
Some good work, a few changes, but is also missing the crucial Calculate function (I know @make-it-git is working on something along these lines now) so this still needs to come in here

2017-07-18 22:08 UTC, darrynten commented on src/Models/SupplierAdjustment.php
> +use DarrynTen\SageOne\Models\ModelCollection;
Why do you need the collection here?

2017-07-18 22:08 UTC, darrynten commented on src/Models/SupplierAdjustment.php
> +}
You're missing custom methods again, the Calculate call is not yet implemented here

https://accounting.sageone.co.za/api/1.1.2/Help/Api/POST-SupplierAdjustment-Calculate

2017-07-18 22:08 UTC, darrynten commented on tests/SageOne/Models/SupplierAdjustmentModelTest.php
> +use DarrynTen\SageOne\Request\RequestHandler;
I don't see this import being used here?

2017-07-18 22:08 UTC, darrynten commented on tests/SageOne/Models/SupplierAdjustmentModelTest.php
> +            $this->assertEquals($model1->Supplier->category->modified->format('Y-m-d'), '2017-07-18');
`Supplier` should be `supplier` with no capital S

2017-07-18 22:08 UTC, darrynten commented on tests/SageOne/Models/SupplierAdjustmentModelTest.php
> +            'Supplier' => [
This mustn't have a capital S

2017-07-18 22:08 UTC, darrynten commented on tests/mocks/SupplierAdjustment/GET_SupplierAdjustment_Get.json
> +  "TotalResults": 1,
You didn't change this number to be bigger than the returned results, see #45

2017-07-18 22:08 UTC, darrynten commented on tests/mocks/SupplierAdjustment/GET_SupplierAdjustment_Get.json
> +      "ID": 1,
You didn't change the details in this second result to be different to the first result, see #45

2017-07-19 07:47 UTC, igorsergiichuk commented on src/Models/SupplierAdjustment.php
> +use DarrynTen\SageOne\Models\ModelCollection;
deleted, redundant

2017-07-19 07:58 UTC, igorsergiichuk commented on tests/SageOne/Models/SupplierAdjustmentModelTest.php
> +use DarrynTen\SageOne\Request\RequestHandler;
AccountCategory - take a look at line 286;
TaxType - take a look at line 268;
SupplierCategory - take a look at line 216;
RequestHandler will be deleted as redundant.

2017-07-19 17:41 UTC, darrynten commented on src/Models/SupplierAdjustment.php
> +}
See #48 for insight into calculate, also sent details on slack

2017-07-19 19:26 UTC, igorsergiichuk commented on src/Models/SupplierAdjustment.php
> +}
thanks. added

2017-07-19 19:30 UTC, igorsergiichuk commented on tests/mocks/SupplierAdjustment/GET_SupplierAdjustment_Get.json
> +  "TotalResults": 1,
Done!

2017-07-19 19:56 UTC, darrynten requested changes
Some minor changes, but nice job!

2017-07-19 19:56 UTC, darrynten commented on tests/SageOne/Models/SupplierAdjustmentModelTest.php
> +        $modelData= json_decode(file_get_contents(__DIR__ . '/../../mocks/SupplierAdjustment/POST_SupplierAdjustment_Calculate_REQ.json'));
Missing space before the `=`

2017-07-19 19:56 UTC, darrynten commented on tests/SageOne/Models/SupplierAdjustmentModelTest.php
> +        $calculated = $model->calculate();
Could you possibly add tests here for the state of the `$calculated` result directly after `calculate()` is called and before you load it into the next model?

2017-07-19 20:17 UTC, igorsergiichuk commented on tests/SageOne/Models/SupplierAdjustmentModelTest.php
> +        $calculated = $model->calculate();
done

2017-07-19 20:40 UTC, darrynten requested changes

2017-07-19 20:40 UTC, darrynten commented on tests/SageOne/Models/SupplierAdjustmentModelTest.php
> +        $this->assertEquals($model->id, 1);
You need to test what `$calculated` looks like, not what `$model` looks like

2017-07-20 11:51 UTC, darrynten approved these changes
Congratulations on your first 'complex' model! 🍾

2017-07-20 11:53 UTC, darrynten requested changes
Wait, needs a checkmark in README

2017-07-20 11:57 UTC, darrynten approved these changes

2017-07-20 12:02 UTC, merged