Company entity type
darrynten/sage-one-php pull request #58
Opened 2017-07-19 09:57 UTC by kiproping

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

## The problem
Company entity type model was missing

## How I resolved it
Added company entity type

## How to verify it

testing

## Questions

None

## Notes

...

Notify the following people: @darrynten

2017-07-19 10:28 UTC, fergusdixon requested changes
Mocks need to be updated

2017-07-19 10:28 UTC, fergusdixon commented on tests/mocks/CompanyEntityType/GET_CompanyEntityType_Get.json
> +      "ID": 1,
Results[0] and results[1] should have unique data.

2017-07-19 11:23 UTC, fergusdixon submitted a review, later dismissed

2017-07-19 15:52 UTC, darrynten requested changes
There's some double quotes that should be single quotes but other than that looking great!

2017-07-19 15:52 UTC, darrynten commented on tests/SageOne/Models/CompanyEntityTypeModelTest.php
> +            $this->assertEquals("sample string 3", $model->name);
These should be single quotes

2017-07-20 08:08 UTC, darrynten approved these changes
Nice one! :D

2017-07-20 10:53 UTC, merged