Account balance model
darrynten/sage-one-php pull request #59
Opened 2017-07-19 10:51 UTC by make-it-git

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #54 (partially)

## The problem

SageOne is very inconsistent in methods/response so I added dummy model for response from getAccountBudgets()

Also all() method requires POST (not GET).

Notify the following people: @darrynten

2017-07-19 15:57 UTC, darrynten requested changes
I really like the way you fixed the problem here.

The only thing we need is for new changes to be documented in Readme and in ExampleModel.

@fergusdixon @kiproping @igorsergiichuk take note of this clever change :)

2017-07-19 15:57 UTC, darrynten commented on src/BaseModel.php
> +     * Example AccountBalance all() requires POST method
I think this is very important, can you please add a note to the README in the relevant section?

Strange inconsistencies :)

2017-07-19 15:57 UTC, darrynten commented on src/BaseModel.php
> +        $results = $this->request->request($this->featureMethods['all'], $this->endpoint, 'Get');
I like the way you solved it, but it's going to be crucial to document it sufficiently in the Example model and in the Readme

2017-07-20 09:24 UTC, make-it-git commented on src/BaseModel.php
> +        $results = $this->request->request($this->featureMethods['all'], $this->endpoint, 'Get');
@darrynten done

2017-07-20 10:42 UTC, darrynten commented on src/BaseModel.php
> +        $results = $this->request->request($this->featureMethods['all'], $this->endpoint, 'Get');
@make-it-git there are some conflicts in this branch that need to be resolved before we can merge it in

2017-07-20 11:46 UTC, darrynten commented on src/Models/AccountBalance.php
> +    public function getAccountBudgetsById($id)
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Avoid variables with short names like $id. Configured minimum length is 3.](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=785392)

2017-07-20 11:46 UTC, darrynten commented on tests/SageOne/Models/AccountBalanceModelTest.php
> +
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Whitespace found at end of line](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=785392)

2017-07-20 11:46 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +    protected function verifyGetAll(string $class, callable $whatToCheck, string $method = 'GET', string $requestMock = null)
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Line exceeds 120 characters; contains 125 characters](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=785392)

2017-07-20 11:46 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +        } else {
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [The method verifyGetAll uses an else expression. Else is never necessary and you can simplify the code to work without else.](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=785392)

2017-07-20 11:47 UTC, darrynten commented
![Codacy](https://www.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- tests/SageOne/Models/BaseModelTest.php  1
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=785392&bid=4951591)

2017-07-20 11:47 UTC, darrynten commented on src/Models/AccountBalance.php
> +    public function getAccountBudgetsById($id)
this one is invalid

2017-07-20 11:48 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +    protected function verifyGetAll(string $class, callable $whatToCheck, string $method = 'GET', string $requestMock = null)
invalid

2017-07-22 11:40 UTC, make-it-git commented
@darrynten merge please

2017-07-23 12:50 UTC, darrynten commented
@make-it-git there are still change requests on this PR 😄

2017-07-23 12:55 UTC, darrynten requested changes
Highlighting the requested changes

2017-07-23 12:55 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +        } else {
@make-it-git here

2017-07-23 12:55 UTC, darrynten commented on tests/SageOne/Models/AccountBalanceModelTest.php
> +
@make-it-git here

2017-07-24 08:13 UTC, darrynten approved these changes
Really great work here!

2017-07-24 08:13 UTC, merged