Analysis type
darrynten/sage-one-php pull request #61
Opened 2017-07-21 08:23 UTC by fergusdixon

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #52 

## The problem
AnalysisType model was missing
...

## How I resolved it
Added AnalysisType model with mocks and tests
...

Notify the following people: @darrynten

2017-07-21 08:24 UTC, fergusdixon commented on .gitignore
> -composer.lock
I changed IDEs and it did this, is that okay?

2017-07-21 08:45 UTC, darrynten commented on .gitignore
> -composer.lock
You should revert this, it's best to not commit that at this stage of development (we put it back later)

2017-07-21 08:51 UTC, darrynten requested changes
Some minor requests and questions

2017-07-21 08:51 UTC, darrynten commented on .gitignore
> +.idea/
Strange that these moves, but cool - and good one on ignoring `.idea`

2017-07-21 08:51 UTC, darrynten commented on src/Models/AnalysisType.php
> +    public function saveBatch()
What's going on with this?

Missing a docblock, and what does it actually POST through?

2017-07-21 08:51 UTC, darrynten commented on tests/SageOne/Models/AnalysisTypeModelTest.php
> +            'type' => 'integer',
Indentation

2017-07-21 08:51 UTC, darrynten commented on tests/SageOne/Models/AnalysisTypeModelTest.php
> +        $this->verifySave(AnalysisType::class, function ($model) {
Is there a reason this callable is empty?

2017-07-21 08:54 UTC, fergusdixon commented on .gitignore
> +.idea/
So do I need to revert it?

2017-07-21 09:02 UTC, fergusdixon commented on tests/SageOne/Models/AnalysisTypeModelTest.php
> +        $this->verifySave(AnalysisType::class, function ($model) {
The verifySave populates the object, so I didn't see the point of doing the usual


            $model->id = 1;
            $model->analysisTypeId = 2;
            $model->description = 'sample string 3';
        }, function ($savedModel) {
            $this->assertInstanceOf(AnalysisCategory::class, $savedModel);
            $this->assertEquals(1, $savedModel->id);
            $this->assertEquals(2, $savedModel->analysisTypeId);
            $this->assertEquals('sample string 3', $savedModel->description);
        });
`
Is it necessary for the tests?

2017-07-21 09:08 UTC, darrynten commented on tests/SageOne/Models/AnalysisTypeModelTest.php
> +        $this->verifySave(AnalysisType::class, function ($model) {
I'm actually not 100% sure, @make-it-git will know more than me about that

2017-07-21 09:30 UTC, kiproping commented on tests/SageOne/Models/AnalysisTypeModelTest.php
> +        $this->verifySave(AnalysisType::class, function ($model) {
I also thing it's redundant. It populates the object second time for no reason.

2017-07-21 09:33 UTC, fergusdixon commented on tests/SageOne/Models/AnalysisTypeModelTest.php
> +        $this->verifySave(AnalysisType::class, function ($model) {
Unless it's testing variable assignment?

2017-07-21 09:35 UTC, fergusdixon commented on .gitignore
> -composer.lock
So just revert the -composer.lock?

2017-07-21 09:44 UTC, darrynten commented on tests/SageOne/Models/AnalysisTypeModelTest.php
> +        $this->verifySave(AnalysisType::class, function ($model) {
It could possibly be, perhaps we should wait to hear what @make-it-git has to say about it :D

2017-07-22 10:46 UTC, make-it-git commented on tests/SageOne/Models/AnalysisTypeModelTest.php
> +        $this->verifySave(AnalysisType::class, function ($model) {
Yes, it's testing variable assignment

2017-07-23 12:52 UTC, darrynten requested changes
I'm not sure what the saveBatch method is doing

2017-07-23 12:52 UTC, darrynten commented on src/Models/AnalysisType.php
> +        return $this->request->request('POST', $this->endpoint, 'SaveBatch');
What gets passed to this request?

2017-07-24 08:00 UTC, fergusdixon commented on src/Models/AnalysisType.php
> +        return $this->request->request('POST', $this->endpoint, 'SaveBatch');
I wasn't 100% sure how the existing framework we've built handles body vs URI parameters, so I found https://accounting.sageone.co.za/api/1.1.2/Help/Api/POST-SupplierAdjustment-Calculate that does a similar function and imitated it.

2017-07-24 08:07 UTC, fergusdixon commented on tests/SageOne/Models/AnalysisTypeModelTest.php
> +            $model->active = true;
To set variables in the collection I tried to implement a __set method but I couldn't get it to work, is it worth doing something like:
`$user = createUser();
$role = $user->role;
$role->rolename = 'Test';` to get around that?

2017-07-24 08:45 UTC, darrynten submitted a review, later dismissed

2017-07-24 08:48 UTC, darrynten commented
As discussed with @fergusdixon the way that Sage do the batch saving of AnalysisType - the model is singular but has a batch call on it, and we have not yet encountered the need to have a custom collection of these.

The next PR will be some form of Library Exception getting thrown here, with details on the inconsistency, relevant links to PRs and discussions like this one, and asking for help to fix the problem, so that the next dev who may need to do a batch save has a head start on fixing this.

2017-07-24 09:33 UTC, darrynten approved these changes

2017-07-24 09:35 UTC, merged