Added Supplier statement model
darrynten/sage-one-php pull request #63
Opened 2017-07-22 13:00 UTC by make-it-git

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

Notify the following people: @darrynten

2017-07-23 12:56 UTC, darrynten commented
This looks dependant on #59 can you confirm if that is the case @make-it-git?

2017-07-23 21:08 UTC, make-it-git commented
Yes, I used some things implemented in that PR

2017-07-24 09:43 UTC, darrynten requested changes
Only some missing trailing commas in SupplierStatement, but the rest looks great!

2017-07-24 09:43 UTC, darrynten commented on src/Models/SupplierStatement.php
> +        'delete' => 'DELETE'
There are some missing trailing commas in this file 😊

2017-07-24 09:43 UTC, darrynten commented on src/Models/SupplierStatementLine.php
> +}
I was wondering when we would have one with no calls :D

2017-07-24 10:43 UTC, darrynten approved these changes

2017-07-24 10:45 UTC, darrynten requested changes
@make-it-git it just needs the README to be updated with the models checked off the list

2017-07-24 11:04 UTC, darrynten approved these changes

2017-07-24 11:04 UTC, merged