Added Company model
darrynten/sage-one-php pull request #66
Opened 2017-07-24 10:25 UTC by make-it-git

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #53

Notify the following people: @darrynten

2017-07-24 10:31 UTC, make-it-git commented
There is invalid warning from codeclimate

2017-07-24 10:45 UTC, darrynten requested changes
Looking good @make-it-git it just needs the README to be updated with the models checked off

2017-07-24 11:54 UTC, make-it-git commented
@darrynten updated

2017-07-24 12:47 UTC, darrynten requested changes

2017-07-24 12:47 UTC, darrynten commented on src/Models/Company.php
> +}
What are we going to do about the `GET Company/Get?includeStatus={includeStatus}` call?

2017-07-24 13:35 UTC, make-it-git commented on src/Models/Company.php
> +}
$model->all(['includeStatus' => true])

2017-07-24 13:56 UTC, make-it-git commented on src/Models/Company.php
> +}
@darrynten check latest commit https://github.com/darrynten/sage-one-php/pull/66/commits/536eaf1be8ef20a9297f0e2012152d0cb08fd9ec

2017-07-24 14:29 UTC, darrynten commented on src/Models/Company.php
> +}
OK great! Can you add some information about this to the README as it isn't immediately clear, but that's very nice, I like it a lot!

2017-07-24 19:05 UTC, darrynten requested changes

2017-07-24 19:05 UTC, darrynten commented on src/Models/Company.php
> +}
@make-it-git this functionality is great, we can get this in if we can add some information about this to the README.md file.

Does the `->get()` call also support this functionality?

Very nice

2017-07-25 06:31 UTC, make-it-git commented
@darrynten updated

2017-07-25 07:09 UTC, darrynten approved these changes

2017-07-25 07:09 UTC, darrynten commented
@make-it-git most excellent! Thanks

2017-07-25 07:09 UTC, merged