Delete response
darrynten/sage-one-php pull request #68
Opened 2017-07-24 11:52 UTC by make-it-git

## Overview

| Q                 | A
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | yes
| Fixed issues      | #65 

## Notes

Need to find some API which does not allow deletion to verify what is returned

...

Notify the following people: @darrynten

2017-07-24 12:52 UTC, darrynten commented on src/Request/RequestHandler.php
> +        }
What does the response from delete look like?

2017-07-24 14:50 UTC, darrynten commented
Hi @make-it-git there's a conflict on this PR :) thanks

2017-07-24 19:36 UTC, make-it-git commented on src/Request/RequestHandler.php
> +        }
Empty response with http code 204

2017-07-25 10:04 UTC, darrynten requested changes

2017-07-25 10:04 UTC, darrynten commented on src/BaseModel.php
> +        return false;
This line is not being reached by unit tests @make-it-git

2017-07-25 11:06 UTC, make-it-git commented on src/BaseModel.php
> +        return false;
Done, do not no yet how to test delete() correctly so for now tests for http code 300 (which is invalid, of course)

2017-07-25 11:51 UTC, darrynten commented
Test is failing at

DarrynTen\SageOne\Tests\SageOne\Models\CompanyNoteModelTest::testDelete
true does not match expected type "object".

2017-07-25 12:36 UTC, make-it-git commented
@darrynten merge is available

2017-07-25 12:40 UTC, darrynten approved these changes
Looking good! @fergusdixon @igorsergiichuk @kiproping this is what we've been waiting for 😀

2017-07-25 12:40 UTC, merged

2017-07-25 13:03 UTC, kiproping commented
![Yaaaaaay](http://wpmedia.nationalpost.com/2016/03/giphy1.gif?w=640)