Supplier ageing
darrynten/sage-one-php pull request #71
Opened 2017-07-24 16:08 UTC by kiproping

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #55 (partially)

## The problem

Supplier ageing model was lacking

## How I resolved it

Added the model

## How to verify it

Test

## Questions

* Testing this date format `2017-07-11T00:00:00Z` 
* Some models don't actually have endpoints e.g `SupplierAgeingRequest`. But I just added the variable because it's required.
* added `DocumentType` constants in the ageingTransaction model. Not sure where I would put them.

Notify the following people: @darrynten @fergusdixon

2017-07-24 18:55 UTC, darrynten requested changes
Some small changes, looking good so far though

2017-07-24 18:55 UTC, darrynten commented on src/Models/AgeingTransaction.php
> +        'documentNumber'=>[
You're missing spaces between `'` and `=>` and `[`

2017-07-24 18:55 UTC, darrynten commented on src/Models/AgeingTransaction.php
> +    const Ignored = -1;
Where are these actually used/referenced?

2017-07-24 18:55 UTC, darrynten commented on src/Models/SupplierAgeing.php
> +    public function getSummary($supplierAgeingRequest)
What does `supplierAgingRequest` look like? Where does it come from?

It seems to me that it would be based on the properties of this class, where is that being built up?

Excuse me if I've misunderstood 😆

2017-07-24 18:55 UTC, darrynten commented on tests/SageOne/Models/SupplierAgeingModelTest.php
> +        $supplierAgeingSummary = $supplierAgeing->getSummary($supplierAgeingRequest);
The request should be based off the properties of the object, _not_ a fresh JSON string that a developer would have to pass to the method 😎

2017-07-25 11:39 UTC, kiproping commented on src/Models/AgeingTransaction.php
> +    const Ignored = -1;
The site is throwing errors but its [DocumentType](https://accounting.sageone.co.za/api/1.1.2/Help/ResourceModel?modelName=DocumentType) referenced here [AgeingTransaction](https://accounting.sageone.co.za/api/1.1.2/Help/ResourceModel?modelName=AgeingTransaction)

2017-07-25 11:46 UTC, kiproping commented on src/Models/SupplierAgeing.php
> +    public function getSummary($supplierAgeingRequest)
This is the supplierAgeingRequest [model](https://accounting.sageone.co.za/api/1.1.2/Help/ResourceModel?modelName=SupplierAgeingRequestModel), Its posted to the getSummary function as [here ](https://accounting.sageone.co.za/api/1.1.2/Help/Api/POST-SupplierAgeing-GetSummary). It's based on the properties of another class, but the POST method requires an array, so I was thinking the getSummary method could  receive an array by whoever is calling it. How best should I go about it?

2017-07-25 11:52 UTC, darrynten commented on src/Models/SupplierAgeing.php
> +    public function getSummary($supplierAgeingRequest)
@make-it-git and @fergusdixon can you guys please take a look at this? Thanks!

2017-07-25 12:18 UTC, fergusdixon commented on src/Models/SupplierAgeing.php
> +    public function getSummary($supplierAgeingRequest)
Looks like supplierAgeing is a search class, using that special request model to return models that are supplierAgeing. This implies to me that it can't build the request from itself as @darrynten suggested because it is the returning Model. The array seems to be the most simple way to do it like @kiproping did in his tests. Maybe a safer way to do it would be to make the request through __construct with checks to make sure all fields are valid?

2017-07-25 12:19 UTC, fergusdixon commented on tests/SageOne/Models/SupplierAgeingModelTest.php
> +        $supplierAgeingSummary = $supplierAgeing->getSummary($supplierAgeingRequest);
Would passing the values through an ageingRequest constructor fix this?

2017-07-26 09:46 UTC, darrynten requested changes
Please see #77

2017-07-26 09:46 UTC, darrynten commented on src/Models/AgeingTransaction.php
> +     * @link https://accounting.sageone.co.za/api/1.1.2/Help/ResourceModel?modelName=DocumentType
This link is broken for me

2017-07-26 09:52 UTC, kiproping commented on src/Models/AgeingTransaction.php
> +     * @link https://accounting.sageone.co.za/api/1.1.2/Help/ResourceModel?modelName=DocumentType
Some links go down randomly, I dont know why. I have a mirror of the documenatation pages here though its not nice viewing raw html. https://github.com/kiproping/sageondocs/blob/master/accounting.sageone.co.za/api/1.1.2/Help/ResourceModel%3FmodelName%3DDocumentType.

2017-07-26 10:04 UTC, darrynten commented
@kiproping 

>  Some models don't actually have endpoints e.g SupplierAgeingRequest. But I just added the variable because it's required.

Does a `null` value for endpoint not work?

2017-07-26 13:51 UTC, darrynten approved these changes
Looking good

2017-07-26 14:50 UTC, darrynten commented
Overriding Codacy check, service is having issues

2017-07-26 14:50 UTC, merged