Account task recurrence
darrynten/sage-one-php pull request #72
Opened 2017-07-24 20:30 UTC by igorsergiichuk

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

## The problem

AccountTaskRecurrence Model was absent

## How I resolved it

Added AccountTaskRecurrence

## How to verify it

Test it.

Notify the following people: @darrynten

2017-07-24 22:02 UTC, darrynten requested changes
Small change, and question about where the mocks are for this.

2017-07-24 22:02 UTC, darrynten commented on src/Models/AccountTaskRecurrence.php
> + * Supplier Model
This isn't the supplier model :)

2017-07-24 22:02 UTC, darrynten commented on tests/SageOne/Models/AccountTaskRecurrenceModelTest.php
> +            // TODO do actual checks
This PR needs to wait for #68 so it can update this method test before going in.

Looking good so far though :D

2017-07-25 07:20 UTC, darrynten commented on tests/SageOne/Models/AccountTaskRecurrenceModelTest.php
> +            // TODO do actual checks
@igorsergiichuk #68 has been merged in and you can update this delete test with the new standard version.

2017-07-25 08:13 UTC, darrynten requested changes

2017-07-25 08:13 UTC, darrynten commented on tests/SageOne/Models/AccountantTaskRecurrenceModelTest.php
> +
This test isn't doing anything :D 

Have another look at #68

2017-07-25 09:22 UTC, darrynten requested changes

2017-07-25 09:22 UTC, darrynten commented on tests/SageOne/Models/AccountantTaskRecurrenceModelTest.php
> +            $this->assertEquals($model->id, 10);
This is still incorrect.

See the new way of doing it in #68 

https://github.com/darrynten/sage-one-php/pull/68/files#diff-b245b15b25cd8029058ac47179f94227R597

2017-07-25 09:39 UTC, igorsergiichuk commented on tests/SageOne/Models/AccountantTaskRecurrenceModelTest.php
> +            $this->assertEquals($model->id, 10);
@darrynten 
The response of the TravisCI and PhpUnit to requested changes:
`1) DarrynTen\SageOne\Tests\SageOne\Models\AccountantTaskRecurrenceModelTest::testDelete

TypeError: Argument 3 passed to DarrynTen\SageOne\Tests\SageOne\Models\BaseModelTest::verifyDelete() must be callable, boolean given, called in /home/travis/build/darrynten/sage-one-php/tests/SageOne/Models/AccountantTaskRecurrenceModelTest.php on line 200`
Should I revert to privious version?

2017-07-25 10:01 UTC, darrynten commented on tests/SageOne/Models/AccountantTaskRecurrenceModelTest.php
> +            $this->assertEquals($model->id, 10);
You need to bring in latest dev first

2017-07-25 14:09 UTC, darrynten approved these changes
Good job!

2017-07-25 14:09 UTC, darrynten commented on tests/SageOne/Models/AccountantTaskRecurrenceModelTest.php
> +        $this->verifyDelete(AccountantTaskRecurrence::class, 10, true);
Nice! :D

2017-07-25 14:09 UTC, merged