Additional item price Model
darrynten/sage-one-php pull request #73
Opened 2017-07-25 09:23 UTC by igorsergiichuk

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

## The problem

AdditionalItemPrice Model was absent

## How I resolved it

Added AdditionalItemPrice

## How to verify it

Test it

## Notes

Check the delete tests please

Notify the following people: @darrynten

2017-07-25 09:25 UTC, darrynten requested changes

2017-07-25 09:25 UTC, darrynten commented on src/Models/AdditionalItemPrice.php
> +        'delete' => true
Missing a trailing comma here :)

2017-07-25 09:25 UTC, darrynten commented on tests/SageOne/Models/AdditionalItemPriceModelTest.php
> +        $this->verifyDelete(AdditionalItemPrice::class, 1, function ($model) {
See new way of testing delete in #68

2017-07-25 14:24 UTC, fergusdixon requested changes
Just some changes to mocks for this model and the model from #72

2017-07-25 14:24 UTC, fergusdixon commented on tests/mocks/AdditionalItemPrice/GET_AdditionalItemPrice_Get.json
> +      "AdditionalPriceListId": 5
All fields need to be unique, update these and the mocks from #72 in this pr please

2017-07-25 18:15 UTC, darrynten requested changes
Minor change request

2017-07-25 18:15 UTC, darrynten commented on README.md
> +  - [x] Additional Item Price *
It's great that you added it here, but you must also remember to remove it from here:

https://github.com/darrynten/sage-one-php/pull/73/files#diff-04c6e90faac2675aa89e2176d2eec7d8R342

2017-07-25 18:35 UTC, igorsergiichuk commented on README.md
> +  - [x] Additional Item Price *
Done

2017-07-26 07:54 UTC, darrynten approved these changes

2017-07-26 07:56 UTC, fergusdixon approved these changes
Good work!

2017-07-26 09:53 UTC, merged