Asset note model
darrynten/sage-one-php pull request #75
Opened 2017-07-25 11:01 UTC by igorsergiichuk

# Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

## The problem

AssetNote model was absent

## How I resolved it

Added AssetNote model

## How to verify it

Test it!

Notify the following people: @darrynten

2017-07-25 18:16 UTC, darrynten requested changes
Some minor change requests

2017-07-25 18:16 UTC, darrynten commented on README.md
> +  - [x] Asset Note *
See #73 about removing it from further down the README

2017-07-25 18:16 UTC, darrynten commented on tests/SageOne/Models/AssetNoteModelTest.php
> +            $this->assertEquals($model->subject, "sample string 3");
These should be single quoted

2017-07-25 18:16 UTC, darrynten commented on tests/SageOne/Models/AssetNoteModelTest.php
> +            $this->assertEquals($model1->subject, "sample string 3");
Single quotes

2017-07-25 18:16 UTC, darrynten commented on tests/SageOne/Models/AssetNoteModelTest.php
> +            $model->subject = "sample string 3";
Some more single quotes

2017-07-25 18:44 UTC, igorsergiichuk commented on tests/SageOne/Models/AssetNoteModelTest.php
> +            $this->assertEquals($model->subject, "sample string 3");
done

2017-07-25 18:44 UTC, igorsergiichuk commented on tests/SageOne/Models/AssetNoteModelTest.php
> +            $this->assertEquals($model1->subject, "sample string 3");
done

2017-07-25 18:44 UTC, igorsergiichuk commented on tests/SageOne/Models/AssetNoteModelTest.php
> +            $model->subject = "sample string 3";
done

2017-07-26 07:55 UTC, darrynten approved these changes

2017-07-26 07:55 UTC, merged