Added Supplier Invoice Model
darrynten/sage-one-php pull request #82
Opened 2017-07-27 07:28 UTC by make-it-git

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

Notify the following people: @darrynten

2017-07-27 08:37 UTC, darrynten requested changes
Nice work @make-it-git some small changes and questions

2017-07-27 08:37 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +            } elseif ($method === 'POST' || $method === 'PUT' || $method === 'DELETE') {
I don't think the `elseif` is 100% required here

2017-07-27 08:37 UTC, darrynten commented on src/Models/SupplierInvoice.php
> +     *           "Value": "sample string 2"
Do we know how these files are encoded? Are they sent inline b64 or are there form attachments? Or is it perhaps a reference to a file uploaded in a different mechanism?

2017-07-27 08:37 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +        $fullUrl = '//localhost:8082' . $urlWithoutParams;
I think we should sprintf this

2017-07-27 08:37 UTC, darrynten commented on src/Models/SupplierInvoice.php
> +            'nullable' => false,
Should this not be nullable given that it's only in the response? Perhaps even read only too?

2017-07-27 10:29 UTC, make-it-git commented on src/Models/SupplierInvoice.php
> +     *           "Value": "sample string 2"
Not yet

2017-07-27 10:30 UTC, darrynten commented on src/Models/SupplierInvoice.php
> +     *           "Value": "sample string 2"
I think perhaps that we should add a note about that to the docblock and to the Readme

2017-07-27 13:56 UTC, make-it-git commented
@darrynten there is one problem
\Mockery:subset() fails for 'json' check because json is passed as stdClass
Even if it is the same object contents it treats them as different objects

http://docs.mockery.io/en/latest/reference/argument_validation.html
When matching objects as arguments, Mockery only does the strict === comparison, which means only the same $object will match:

So I do not know easy way to validate that we passed expected arguments to request in POST/PUT/DELETE methods

2017-07-27 19:34 UTC, make-it-git commented
@darrynten any ideas how to test that we passed expected 'json' stdClass?

2017-07-27 22:19 UTC, darrynten commented
@make-it-git I sent you a message on slack about it, let's discuss tomorrow morning - this work is looking really good by the way 😎

2017-07-28 11:25 UTC, darrynten requested changes
I think we need another more robust http verb check

2017-07-28 11:25 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +            } else {
I think we should check that the request is one of the 3 allowed types that can have Json and drop/throw all other verbs

2017-07-28 12:16 UTC, darrynten commented on tests/SageOne/Models/SupplierInvoiceModelTest.php
> +    public function testAll()
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [The method testAll() has 335 lines of code. Current threshold is set to 100. Avoid really long methods.](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=804082)

2017-07-28 12:16 UTC, darrynten commented on tests/SageOne/Models/SupplierInvoiceModelTest.php
> +    public function testAttributes()
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [The method testAttributes() has 273 lines of code. Current threshold is set to 100. Avoid really long methods.](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=804082)

2017-07-28 12:16 UTC, darrynten commented on tests/SageOne/Models/SupplierInvoiceModelTest.php
> +class SupplierInvoiceModelTest extends BaseModelTest
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [The class SupplierInvoiceModelTest has 1168 lines of code. Current threshold is 1000. Avoid really long classes.](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=804082)

2017-07-28 12:16 UTC, darrynten commented on tests/SageOne/Models/SupplierInvoiceModelTest.php
> +    public function testGetId()
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [The method testGetId() has 166 lines of code. Current threshold is set to 100. Avoid really long methods.](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=804082)

2017-07-28 12:16 UTC, darrynten commented on tests/SageOne/Models/SupplierInvoiceModelTest.php
> +    public function testSave()
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [The method testSave() has 170 lines of code. Current threshold is set to 100. Avoid really long methods.](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=804082)

2017-07-28 12:16 UTC, darrynten commented on tests/SageOne/Models/SupplierInvoiceModelTest.php
> +    public function testCalculate()
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [The method testCalculate() has 172 lines of code. Current threshold is set to 100. Avoid really long methods.](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=804082)

2017-07-28 12:16 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +            } else {
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [The method verifyGetAll uses an else expression. Else is never necessary and you can simplify the code to work without else.](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=804082)

2017-07-28 12:16 UTC, darrynten commented
![Codacy](https://www.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 7
           

Complexity increasing per file
==============================
- tests/SageOne/Models/BaseModelTest.php  6
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/Xpenso/sage-one-php/pullRequest?prid=804082&bid=5000561)

2017-07-28 13:32 UTC, make-it-git commented
@darrynten Fixed

2017-07-28 18:28 UTC, make-it-git commented
@darrynten added better http check

2017-07-28 18:35 UTC, darrynten reviewed
Combine a method and then all good

2017-07-28 18:35 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +            if (!empty($parameters)) {
I think this line and the one above can be combined here and again further down

2017-07-28 18:35 UTC, darrynten commented on tests/SageOne/Models/BaseModelTest.php
> +
Here's the other one. They're actually in a different order to the above one :)

2017-07-28 18:36 UTC, darrynten commented
A method call** sorry :)

2017-07-29 21:20 UTC, darrynten approved these changes

2017-07-29 21:20 UTC, merged