Customer note model
darrynten/sage-one-php pull request #83
Opened 2017-07-27 14:04 UTC by igorsergiichuk

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

## The problem

CustomerNote model was absent

## How I resolved it

Added CustomerNote model

## How to verify it

Test it!

Notify the following people: @darrynten

2017-07-27 22:18 UTC, darrynten requested changes
Just a missing comma, looking good

2017-07-27 22:18 UTC, darrynten commented on src/Models/CustomerNote.php
> +        'delete' => true
There's a missing trailing comma here :)

2017-07-31 09:51 UTC, darrynten requested changes

2017-07-31 09:51 UTC, darrynten commented on tests/mocks/CustomerNote/GET_CustomerNote_Get.json
> +  "TotalResults": 1,
This won't be valid you'll need to match the numbers you can't return more than you have

2017-07-31 11:55 UTC, darrynten requested changes

2017-07-31 11:55 UTC, darrynten commented on tests/mocks/CustomerNote/GET_CustomerNote_Get.json
> +  "TotalResults": 1,
This number is incorrect

2017-07-31 13:04 UTC, igorsergiichuk commented on tests/mocks/CustomerNote/GET_CustomerNote_Get.json
> +  "TotalResults": 1,
done

2017-07-31 14:40 UTC, darrynten approved these changes
🚀

2017-07-31 14:40 UTC, merged