Customer opening balance
darrynten/sage-one-php pull request #84
Opened 2017-07-27 15:37 UTC by igorsergiichuk

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

## The problem

The CustomerOpeningBalance model was absent

## How I resolved it

Add CustomerOpeningBalance model

## How to verify it

Test it!

Notify the following people: @darrynten

2017-07-27 22:16 UTC, darrynten requested changes

2017-07-27 22:16 UTC, darrynten commented on tests/mocks/BankAccountCategory/POST_BankAccountCategory_Save_RESP.json
> +
Is this correct? @fergusdixon do you perhaps know?

2017-07-31 13:14 UTC, fergusdixon commented on tests/mocks/BankAccountCategory/POST_BankAccountCategory_Save_RESP.json
> +
The response has a body,  in this view the mock looks empty but if I check the files in the branch it has a json response?

2017-07-31 13:36 UTC, igorsergiichuk commented on tests/mocks/BankAccountCategory/POST_BankAccountCategory_Save_RESP.json
> +
I've deleted all the Mocks needed for the BankAccountCategory model. There is another branch for that model.

2017-07-31 14:56 UTC, darrynten approved these changes
Nice

2017-07-31 14:56 UTC, merged