Supplier payment
darrynten/sage-one-php pull request #97
Opened 2017-07-31 19:48 UTC by make-it-git

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

Notify the following people: @darrynten

2017-07-31 22:34 UTC, darrynten reviewed
Is this the PR with models in it that you need help with tests for?

2017-07-31 22:34 UTC, darrynten commented on src/Models/BankAccount.php
> +<?php
Don't forget to tick this one off in the README too :)

2017-08-01 06:53 UTC, make-it-git commented on src/Models/BankAccount.php
> +<?php
These models are incomplete (only fields are described, any additional methods not created) so I think we can tick them once tests are done.

2017-08-01 15:55 UTC, darrynten requested changes
@make-it-git you'll be pleased to know that @igorsergiichuk will be making tests for the rest of the models in here and opening a PR into this one for these tests:

* BankAccount
* BankFeedAccountGroup
* BankFeedAccount
* BankAccountCategory

He's really quick so this will be soon 🚀

@fergusdixon check this too :D

2017-08-01 15:55 UTC, darrynten commented on src/Models/BankAccount.php
> +<?php
OK great, I think we should mark them in the Readme with something like `(partial)` next to the name. What do you think?

2017-08-02 07:26 UTC, make-it-git commented on src/Models/BankAccount.php
> +<?php
@darrynten marked

2017-08-03 11:36 UTC, darrynten approved these changes

2017-08-03 11:36 UTC, merged